package com.cactusbearer;

public enum Command{
    LOOK, HELP, ERROR, SET_CONTEXT, SHOW, ADVANCE_DIALOGUE, BUY, USE, CHANGE_CONNECTION,
    GIVE, TALK, ADMIN_READ, WIN, MOVE, GO, DROP, TAKE, PUT, EXAMINE, INVENTORY, SLOOK
}